### ISSUE TITLE
chapter 04

### ISSUE THREAD

**Issue by fouad09** [GoogleCloudPlatform/data-science-on-gcp#101]
I am having an issue completing the dataflow job.
I am running the following code : 

python3 ./df06.py --bucket <BUCKET_ID> --project <PROJECT_ID>

The job fails systematically with the following error:

S05:flights:out/Write/WriteImpl/DoOnce/Read+flights:out/Write/WriteImpl/InitializeWrite failed., Unable to rename output files from gs://<BUCKET_ID>/flights/temp/ch04timecorr.1602434648.732985/dax-tmp-2020-10-11_09_44_11-12056507475505464176-S05-1-d760919bd33dfadf/tmp-d760919bd33df9f4@DAX.avro to gs://<BUCKET_ID>/flights/temp/ch04timecorr.1602434648.732985/tmp-d760919bd33df9f4@*.avro., Unable to rename "gs://<BUCKET_ID>/flights/temp/ch04timecorr.1602434648.732985/dax-tmp-2020-10-11_09_44_11-12056507475505464176-S05-1-d760919bd33dfadf/tmp-d760919bd33df9f4-shard--try-05e30fce7e7f14ed-endshard.avro" to "gs://<BUCKET_ID>/flights/temp/ch04timecorr.1602434648.732985/tmp-d760919bd33df9f4-00000-of-00001.avro".

The flights and airports  PCollection are:

  airports = (pipeline 
      | 'airports:read' >> beam.io.ReadFromText(airports_filename)
      | 'airports:fields' >> beam.Map(lambda line: next(csv.reader([line])))
      | 'airports:tz' >> beam.Map(lambda fields: (fields[0], addtimezone(fields[21], fields[26])))
   )

   flights = (pipeline 
      | 'flights:read' >> beam.io.ReadFromText (flights_raw_files)
      | 'flights:tzcorr' >> beam.FlatMap(tz_correct, beam.pvalue.AsDict(airports))
   )

I am not sure why a temp file is created and how to fixe the error above.

Thanks

**Comment by fouad09** [comment]
![CHAPTER_04](https://user-images.githubusercontent.com/17675246/95685606-d6cb2600-0bc6-11eb-93db-78be1c16aac0.png)

**Comment by nounchanveasna** [comment]
![image](https://user-images.githubusercontent.com/41176447/97099711-9edfda80-16be-11eb-8907-274baeed1ddb.png)
Yes, I'm also, I don't know how to fix.

**Comment by anton-liseitcev-db** [comment]
the same issue for me, was you able to solve it? Would appreciate any help
