### ISSUE TITLE
Ch 6 Create Cluster extra parameters may be needed

### ISSUE THREAD

**Issue by davezen1** [GoogleCloudPlatform/data-science-on-gcp#110]
Tried creating a cluster and using ssh tunnel and had to make adjustments.
I think the service account is necessary but not positive.

- Specify service account: https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/service-accounts
- Set flag for Jupyter to listen to all instead of the default localhost: https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/cluster-properties

gcloud beta dataproc clusters create \
   --num-workers=2 \
   --scopes=cloud-platform \
   --worker-machine-type=n1-standard-4 \
   --master-machine-type=n1-standard-4 \
   --image-version=1.4 \
   --enable-component-gateway \
   --optional-components=ANACONDA,JUPYTER \
   --region=$REGION \
   --service-account=$SERVICE_ACCOUNT \
   --initialization-actions=$INSTALL \
   --properties=dataproc:jupyter.listen.all.interfaces=true \
   ch6cluster

I don't think this is needed but may be helpful. I used the GCP Console recommended commands to set up the SSH tunnel, which looks like this:

## Create an SSH tunnel using local port 1080
`gcloud compute ssh ch6cluster-m \
  --project=$PROJECT_ID  \
  --zone=$ZONE -- -D 1080 -N`

## Run Chrome and connect through the proxy
`/usr/bin/google-chrome \
  --proxy-server="socks5://localhost:1080" \
  --user-data-dir="/tmp/ch6cluster-m" http://ch6cluster-m:8088`

## For the Jupyter URL the default port is 8123 but to get to the UI (notebooks) I used:
http://ch6cluster-m:8123/gateway/default/jupyter

**Comment by lakshmanok** [comment]
thanks! fixed the ssh.

For accessing JupyterHub, you can now do it directly from the web console. Proxying is not needed.
https://cloud.google.com/dataproc/docs/tutorials/dataproc-hub-users

So, suggesting that instead.
