### ISSUE TITLE
Chapter 2: Getting 500 - Internal Server Error when Running ingest_flights.py

### ISSUE THREAD

**Issue by dylanmpeck** [GoogleCloudPlatform/data-science-on-gcp#119]
Screenshot of results from running `ingest_flights.py`:

![command2](https://user-images.githubusercontent.com/40506467/128434629-763ce84c-04d1-40b6-9749-3fef88029b7f.png)

It looks like the link used to request the data in ingest.py may be broken: 'https://www.transtats.bts.gov/DownLoad_Table.asp?Table_ID=236&Has_Group=3&Is_Zipped=0'.

Receiving a 500 error when trying to access that link.

Is there an alternative link from that site that could be used?

**Comment by lakshmanok** [comment]
Skip this step, and get the data from the bucket. The README files have the
details.

**Comment by dylanmpeck** [comment]
Thanks for the quick response, Lak.

That definitely solves the issue when testing locally, but then the rest of the Qwiklab on this chapter involves the optional content of making a Cloud Function with the python code and setting it to an automated schedule. Following the CF setup instructions from the readme, I'm encountering the same 500 error from ingest_flights.py when testing the cloud function.

<img width="1748" alt="Screen Shot 2021-08-05 at 5 35 02 PM" src="https://user-images.githubusercontent.com/40506467/128438345-e769de28-4c28-472a-b107-49fe7b2530d7.png">

**Comment by lakshmanok** [comment]
looks like the URL has changed a bit.  Can you try starting from

https://www.transtats.bts.gov/DL_SelectFields.asp

to see what the download URL needs to be?

**Comment by dylanmpeck** [comment]
Thanks, Lak!

When do you think this change might make it into the repo?

**Comment by lakshmanok** [comment]
Probably this weekend ...
