### ISSUE TITLE
Chapter 4: Data format 

### ISSUE THREAD

**Issue by huuhuannt1998** [GoogleCloudPlatform/data-science-on-gcp#122]
Hi,

In chapter 2, the URL used to download is expired, and we have a new URL which is here: https://github.com/GoogleCloudPlatform/data-science-on-gcp/issues/119

However, the data format in chapter 4 has been changed. May you update the new input for the BigQuery console? 

Sincerely.

**Comment by lakshmanok** [comment]
1. I am writing a new version of the book and working on Ch 4 now. In the GitHub repo, switch to the edition2 branch and follow the README instructions to see what the changes look like.
2. If you are following Edition 1, please use the data in the bucket by using https://github.com/GoogleCloudPlatform/data-science-on-gcp/blob/main/02_ingest/ingest_from_crsbucket.sh
