### ISSUE TITLE
Chapter 3: csv file format does not match

### ISSUE THREAD

**Issue by huuhuannt1998** [GoogleCloudPlatform/data-science-on-gcp#125]
Lak, 

In chapter 3, when I run "./ingest_from_crsbucket bucketname", the data format of the csv files does not match the file format in create_table.sql. Using the new table using the old version of create_table.sql, it doesn't let me create, but the new version does. However, using the new version create_table.sql doesn't match with the csv files we have from "./ingest_from_crsbucket bucketname". Therefore, we can't do the following steps 

Load the CSV files into this table:
Browse to 201501.csv in your bucket
Specify CSV as the format
bts as the database
flights as the table 

May you take a look at this problem and show me how to fix this? 
Thank you.

**Comment by lakshmanok** [comment]
code updated to Edition 2
