### ISSUE TITLE
Ch10 correct? I think this might need to be Ch11? 

### ISSUE THREAD

**Issue by graciofilipe** [GoogleCloudPlatform/data-science-on-gcp#135]
https://github.com/GoogleCloudPlatform/data-science-on-gcp/blob/021464769d4523231d55eccbe8e04d2c0a3c4b56/11_realtime/create_traindata.py#L57

**Comment by graciofilipe** [comment]
The generated data as is goes to a ch10 folder. but this is ch11. The next step in "train_on_vertex_ai.py" expects to find the values in ch11.

` all_files = tf.io.gfile.glob('gs://{}/ch11/data/all*.csv'.format(BUCKET))`

**Comment by lakshmanok** [comment]
I think so ... but the reorg has messed things up ... I obviously have the data both in Ch 10 and 11 ... so if you are doing it from a clean environment and can verify, that will be great.

**Comment by graciofilipe** [comment]
Relevant PR here: https://github.com/GoogleCloudPlatform/data-science-on-gcp/pull/136/files
