### ISSUE TITLE
Tensorflow 1.7 

### ISSUE THREAD

**Issue by mshearer0** [GoogleCloudPlatform/data-science-on-gcp#14]
The current version of Tensorflow is 1.7. Models created using this version can't be deployed to the GCP ML Engine.

I fixed this by removing 1.7 and inserting 

REQUIRED_PACKAGES = [
  'tensorflow==1.6',
]
into setup.py

and then deploying with --runtime-version=1.6

You might like to point this out for new users who will download 1.7 by default. I appreciate that versions and compatibility with cloudML will continue to evolve

**Comment by lakshmanok** [comment]
Which page?  I'll get a note added to the PDF version of the book

**Comment by lakshmanok** [comment]
This works as intended in Datalab
