### ISSUE TITLE
Chapter 2: curl: (60) SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by BoHuang2018** [GoogleCloudPlatform/data-science-on-gcp#140]
Just tested the first command line in Chapter2 (the new version), to  issue a HTTP POST downloading a single month data
`% curl -o temp.zip https://transtats.bts.gov/PREZIP/On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2015_3.zip`

Got error: 
```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
``` 

Tested with  Cloud Shell and locally (osx), got the same error 

However, the URL `https://transtats.bts.gov/PREZIP/On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2015_3.zip` works on browser.

**Comment by BoHuang2018** [comment]
Just solved this issue:

Using `-k` flag to avoid SSL error.  The following terminal command works
`curl -k -o temp.zip https://transtats.bts.gov/PREZIP/On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2015_3.zip`

**Comment by lakshmanok** [comment]
code updated to Edition 2
