### ISSUE TITLE
Wide and Deep Model and runtime version.

### ISSUE THREAD

**Issue by mshearer0** [GoogleCloudPlatform/data-science-on-gcp#15]
Wide and Deep Model produces same probabilities regardless of request instance values. Linear and DNN models function correctly.

Model.py:
def get_model(output_dir, nbuckets, hidden_units, learning_rate):
    #return linear_model(output_dir)
    return dnn_model(output_dir)
    #return wide_and_deep_model(output_dir, nbuckets, hidden_units, learning_rate)

Deploy_model.sh:
Need to add --runtime-version=1.6:
gcloud ml-engine versions create ${MODEL_VERSION} --model ${MODEL_NAME} --origin ${MODEL_LOCATION} **--runtime-version=1.6**

**Comment by lakshmanok** [comment]
fixed

**Comment by mshearer0** [comment]
Hi - What was wrong with the Wide and Deep Model ?
