### ISSUE TITLE
Ch9 - training deep neural network - how to attach GPU?

### ISSUE THREAD

**Issue by jgammerman** [GoogleCloudPlatform/data-science-on-gcp#165]
@lakshmanok - regarding my earlier issue (#164), I've ended up manually exporting the data from BQ to cloud storage using the GUI.

The rest of the notebook is working fine, but now I'm training the deep neural network it's awfully slow (I'm still on the first of the 10 epochs and it's not even half way through it after 10 minutes!). 

I'm guessing that the problem is that I'm using CPUs rather than a GPU...on p.322 of the book you state _"Making sure that the Vertex AI Workbench notebook that I’m working on has a GPU attached to it, I can now launch off the training job..."_ but if I'm not mistaken it's not covered in the textbook or notebook how to do this? 

I've already set up my fully-managed notebook to enable an NVIDIA T4 GPU, but I believe that it won't be attached automatically without me doing something else.

![image](https://user-images.githubusercontent.com/8484188/218147610-1ba88ede-ecda-4122-bdbb-0efafeda0348.png)
  

The GC docs refer to creating a separate [CustomJob ](https://cloud.google.com/vertex-ai/docs/training/configure-compute#create_custom_job_gpus-console) to achieve this - is that what you did or is there a quicker way?

**Comment by lakshmanok** [comment]
When you launch the notebook instance, make sure to specify a machine type
with a GPU. You can also stop the instance, add a GPU, and then restart it

thanks,
Lak

**Comment by jgammerman** [comment]
Still no quicker I'm afraid - one epoch is taking about 20 minutes...

My notebook instance now comes with a GPU:

![image](https://user-images.githubusercontent.com/8484188/218158237-96e10cdc-9f9a-4ff9-acd1-36b8cc273cc5.png)

And when starting the notebook I've selected as my kernel Tensorflow 2 (Local), previously it was Python (local) :

![image](https://user-images.githubusercontent.com/8484188/218158380-b91d69d6-ef32-4a56-8de2-9f613672970d.png)

I can't see any other options for specifying that my GPU should be used...

**Comment by jgammerman** [comment]
Also - I have a really dumb question but it's come up before in this book so I may as well ask it now...

I'd like to see the CPU/GPU usage of the VM that my notebook is running on. In other cloud platforms (eg. Azure) you have to connect the notebook to a VM manually every time, which makes this easy to do. 

But in GCP, everything seems to happen in the background and it's not clear how to inspect your VM....if I go to the VM Instances API in the console, it looks like I don't have any:

![image](https://user-images.githubusercontent.com/8484188/218159743-09a7e68a-de0b-4fbf-ace3-b8a51d0248c9.png)

Please could you advise? Sorry if this is a stupid question but I'm guessing it's not just me who is confused!

**Comment by lakshmanok** [comment]
(1) If you didn't change the line that says DEVELOP=True in the notebook,
each epoch should take less than a minute.  By any chance, are the compute
on the notebook & the bucket region different?
(2) you can look at notebook gpu/cpu usage etc. by click on the notebook
name (in the Vertex Workbench area), and selecting the "Monitoring" tab

thanks
Lak

**Comment by jgammerman** [comment]
1) Oh I changed DEVELOP=True to DEVELOP=False after successfully running 2 epochs very quickly, under a minute as you said. The flow of the Jupyter notebook is somewhat different to the textbook chapter so I thought that was what I was supposed to do - maybe not!

2) Unfortunately I can't see any Monitoring tab, only Logs:

![image](https://user-images.githubusercontent.com/8484188/218164225-ad6f5059-dd10-4932-8684-687c1ac75053.png)

Thanks for these quick response by the way...I'll be sure to mention them in the glowing Amazon review I give of the book once I'm done with it!

**Comment by lakshmanok** [comment]
Yeah, you don't need to run on the full dataset.  You can just try it out
on a small sample.
In later chapters, I'll have you copy over my model that was trained over
the whole thing.

Re: monitoring: you are using managed notebooks rather than the
user-managed notebooks that I was using:
   https://cloud.google.com/vertex-ai/docs/workbench/managed/introduction
Part of the control you give up when you ask Vertex AI to manage the
notebook lifecycle is that it runs it in a tenant project, so your ability
to monitor is limited
Think of managed notebooks as being like Google Colab.

Lak

**Comment by jgammerman** [comment]
I see! Thank you Lak.
