### ISSUE TITLE
Install Google Cloud Dataflow prior to df06.py

### ISSUE THREAD

**Issue by mshearer0** [GoogleCloudPlatform/data-science-on-gcp#19]
Had to run

sudo pip install google-cloud-dataflow

before 

    ./df06.py --project=$DEVSHELL_PROJECT_ID --dataset=flights2016 --bucket=BUCKETNAME

**Comment by juancop** [comment]
Thank you! That's the line that's missing to succeed in this chapter. It works fine. 

./df06.py --project=$DEVSHELL_PROJECT_ID --dataset=flights --bucket=BUCKETNAME

**Comment by lakshmanok** [comment]
Please run ./install_packages.sh which installs  'apache-beam[gcp]'
