### ISSUE TITLE
simulate.py  not working in cloud shell

### ISSUE THREAD

**Issue by wortel3** [GoogleCloudPlatform/data-science-on-gcp#21]
Error thrown: 
Traceback (most recent call last):
  File "simulate.py", line 22, in <module>
    from google.cloud import pubsub
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub/__init__.py", line 30, in <module>
    from google.cloud.pubsub.client import Client
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub/client.py", line 21, in <module>
    from google.cloud.pubsub._http import Connection
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub/_http.py", line 25, in <module>
    from google.cloud.iterator import HTTPIterator
ImportError: No module named iterator

When running install.sh: 
google-cloud-pubsub 0.26.0 has requirement google-cloud-core<0.26dev,>=0.25.0, but you'll have google-cloud-core 0.28.1 which is incompatible.
gapic-google-cloud-pubsub-v1 0.15.4 has requirement oauth2client<4.0dev,>=2.0.0, but you'll have oauth2client 4.1.2 which is incompatible.
proto-google-cloud-pubsub-v1 0.15.4 has requirement oauth2client<4.0dev,>=2.0.0, but you'll have oauth2client 4.1.2 which is incompatible.
google-api-core 1.1.2 has requirement setuptools>=34.0.0, but you'll have setuptools 33.1.1 which is incompatible.
proto-google-cloud-datastore-v1 0.90.4 has requirement oauth2client<4.0dev,>=2.0.0, but you'll have oauth2client 4.1.2 which is incompatible.
googledatastore 7.0.1 has requirement oauth2client<4.0.0,>=2.0.1, but you'll have oauth2client 4.1.2 which is incompatible.

**Comment by lakshmanok** [comment]
Unfortunately, this depends on what you have already installed in CloudShell ...

Try using "virtualenv" and then run simulate.py in virtualenv

https://virtualenv.pypa.io/en/stable/
