### ISSUE TITLE
02_ingest/monthlyupdate/ingest_flights.py

### ISSUE THREAD

**Issue by Rakatashii** [GoogleCloudPlatform/data-science-on-gcp#22]
Hi, 
I'm currently reading your book and having some trouble with this executable. To be honest, I'm not very familiar with Python. This is the error I'm getting (also with ./ingest_flights.py --help):
`Traceback (most recent call last):
  File "./ingest_flights.py", line 25, in <module>
    from google.cloud import storage
ImportError: No module named google.cloud`
I have the cloud SDK and python installed so I'm a bit confused on what to do. Unfortunately the answers on SO and the GCP docs didn't help me much, so I'm wondering if you could advise.

**Comment by lakshmanok** [comment]
This is meant to be run as part of a web-server.  To run it locally, you would have to install the components we ask Appengine to install:

https://github.com/GoogleCloudPlatform/data-science-on-gcp/blob/master/02_ingest/monthlyupdate/requirements.txt

But just follow the instructions in

https://github.com/GoogleCloudPlatform/data-science-on-gcp/blob/master/02_ingest/README.md

to install this as an AppEngine web application

**Comment by Rakatashii** [comment]
Got it, thank you for the help.
