### ISSUE TITLE
Chapter 3, page 73  - Add zone to SQL create command 

### ISSUE THREAD

**Issue by joozz** [GoogleCloudPlatform/data-science-on-gcp#23]
Current command 

`gcloud sql instances create flights --tier=db-n1-standard-1 --activation-policy=ALWAYS`

Recommendation to add zone: 

`gcloud sql instances create flights --tier=db-n1-standard-1 --activation-policy=ALWAYS --gce-zone=us-central1-a`

to avoid

`WARNING: Starting with release 218.0.0, you will need to specify either a region or a zone to create an instance.`

**Comment by lakshmanok** [comment]
thanks, fixed.
