### ISSUE TITLE
Chapter 4 - df06.py faces default quota limit 

### ISSUE THREAD

**Issue by joozz** [GoogleCloudPlatform/data-science-on-gcp#25]
In case a default project quota on GCP is still in place ("trial" account with free credit), df06.py fails due to  '--max_num_workers=10'. The default quota is 8. 
To make this run, change 
`'--max_num_workers=10',` to `'--max_num_workers=8',` in the df06.py. 
Alternatively, change from "free trial account" - "Upgrade" in IAM - Quotas. 
Documentation: [https://cloud.google.com/compute/quotas](url)

**Comment by lakshmanok** [comment]
thanks, changed.
