### ISSUE TITLE
CreateTrainingDataset9 average arrival delay time is computed without filtering by "isTrain" flag)

### ISSUE THREAD

**Issue by DmitriyLamzin** [GoogleCloudPlatform/data-science-on-gcp#31]
https://github.com/GoogleCloudPlatform/data-science-on-gcp/blob/706104284e12c18e82683b372a031018601d273c/08_dataflow/chapter8/src/main/java/com/google/cloud/training/flights/CreateTrainingDataset9.java#L216

Hello. As we create training set it is reasonable to filter flights by training flag for average arrival delay too.
Otherwise during evaluation we will have not consistent data.
I mean the average arrival delay will already include the delay of the flight we make prediction for. So we shouldn't include anyhow data from evaluation set to training set.

**Comment by lakshmanok** [comment]
This is fine because the prediction of delay is made at the time the flight is *departing*, so the moving average of arrival delays won't include that flight.

That's why we have to filter the departure delays, but don't have to do this for arrival delays.
