### ISSUE TITLE
The www.transtats.bts.gov is down no idea for how long and since when

### ISSUE THREAD

**Issue by bdabrowski** [GoogleCloudPlatform/data-science-on-gcp#32]
Hi, 

The https://www.transtats.bts.gov is down no idea since when. Also I have no information of when or if will be fixed.

I know that is not our responsibility but would be nice to have alternative way to download it in case problem is persisting.
<img width="1069" alt="screenshot 2019-01-13 at 15 22 37" src="https://user-images.githubusercontent.com/3586221/51086420-2907ba80-1747-11e9-81d5-11cd7b5c097d.png">

**Comment by lakshmanok** [comment]
There is an alternative way! Check out:

https://github.com/GoogleCloudPlatform/data-science-on-gcp/blob/master/03_sqlstudio/README.md
