### ISSUE TITLE
Python client library version is too old in cloud shell

### ISSUE THREAD

**Issue by myoshimu** [GoogleCloudPlatform/data-science-on-gcp#35]
Maybe I am missing something but when I tried to run some code in cloud shell, I saw errors because the default installed python client library version is too old.

e.g. simulate.py in chapter 04
```
$  python ./simulate.py --startTime '2015-05-01 00:00:00 UTC' --endTime '2015-05-04 00:00:00 UTC' --speedFactor=30 --project $DEVSHELL_PROJECT_ID
Traceback (most recent call last):
  File "./simulate.py", line 83, in <module>
    dataset =  bqclient.get_dataset( bqclient.dataset('flights') )  # throws exception on failure
AttributeError: 'Client' object has no attribute 'get_dataset'
```

pip freeze shows following:
```
google-cloud-bigquery==0.25.0
google-cloud-pubsub==0.26.0
```

After running pip install --upgrade the code run successfully.
(e.g.)
```
$ pip install --upgrade --user google-cloud-bigquery
$ pip install --upgrade --user google-cloud-pubsub
```
Am I missing some steps?

**Comment by lakshmanok** [comment]
Did you run ./install_packages.sh?

**Comment by myoshimu** [comment]
Yes, I run 04_streaming/simulate/install_packages.sh

**Comment by lakshmanok** [comment]
ah, I see the problem.  Could you add --upgrade to

https://github.com/GoogleCloudPlatform/data-science-on-gcp/blob/master/04_streaming/simulate/install_packages.sh

and issue a PR?
