### ISSUE TITLE
BucketNotFoundException @ Add data to Cloud SQL instance

### ISSUE THREAD

**Issue by SiewLinYap** [GoogleCloudPlatform/data-science-on-gcp#52]
Bucket has been created and it did appear in the console under Storage. 
<img width="490" alt="Screenshot 2019-03-14 at 12 52 35 PM" src="https://user-images.githubusercontent.com/35646492/54332239-3b737700-4658-11e9-82b4-26bcecfa8e85.png">

However, when running in cloud shell with following codes :
<img width="320" alt="Screenshot 2019-03-14 at 12 54 37 PM" src="https://user-images.githubusercontent.com/35646492/54332270-61991700-4658-11e9-8918-66f5cc3cbd56.png">

It showed the error :
<img width="701" alt="Screenshot 2019-03-14 at 12 55 52 PM" src="https://user-images.githubusercontent.com/35646492/54332300-87beb700-4658-11e9-81df-9af11fc00f60.png">

Repeated the lab twice, but still having the same error... Pls advice and rectify. Thanks.

**Comment by lakshmanok** [comment]
Note that the bucket name has qwiklabs-gcp-c924 ... whereas the error message refers to gcp-c924 ... I think your $BUCKET variable is set wrongly in cloudshell
