### ISSUE TITLE
SyntaxError while running df05.py @ Lab ( Processing Data with Google Cloud Dataflow )

### ISSUE THREAD

**Issue by SiewLinYap** [GoogleCloudPlatform/data-science-on-gcp#53]
For lab ( Processing Data with Google Cloud Dataflow), one of the step was to run script df05.py

<img width="417" alt="Screenshot 2019-03-15 at 8 47 10 AM" src="https://user-images.githubusercontent.com/35646492/54400767-67960300-46ff-11e9-9348-113d8514edef.png">

However, it returned SyntaxError coming from one of the function under another file timezonefinder.py

<img width="795" alt="Screenshot 2019-03-15 at 8 49 59 AM" src="https://user-images.githubusercontent.com/35646492/54400776-711f6b00-46ff-11e9-9165-4188281cc5f2.png">

Pls help to check and amend. Thanks.

**Comment by Tobro88** [comment]
Seems to be the same problem as highlighted under #55. Change the install_packages,sh to:

`#!/bin/bash
sudo pip install --upgrade timezonefinder==3.0.0 pytz apache-beam 'apache-beam[gcp]'`
