### ISSUE TITLE
Chapter 4: df06.py didn't create simevents table   

### ISSUE THREAD

**Issue by cesarestradaft** [GoogleCloudPlatform/data-science-on-gcp#63]
Dataflow doesn't show anything.  I go to BigQuery and see the flights dataset but the table simevents is absent.  I run the query and I get this popup message 

Not found: Table data-science-gcp-book-237318:flights.simevents was not found in location US

**Comment by cesarestradaft** [comment]
I reran today Steps taken 1.confirmed that airports.csv.gz was copied into my bucket in /flights/airports 2.reran install_packages.sh to get apache beam reinstalled 3.ran df06.py
Viewed in GCP dataflow, ch04timecorr failed with the following in log after 6 minutes:
Workflow failed. Causes: S04:airports:read/Read+airports:fields+airports:tz failed., A work item was attempted 4 times without success. Each time the worker eventually lost contact with the service. The work item was attempted on: 
  ch04timecorr-04191422-lci6-harness-8txl,
  ch04timecorr-04191422-lci6-harness-8txl,
  ch04timecorr-04191422-lci6-harness-8txl,
  ch04timecorr-04191422-lci6-harness-8txl

**Comment by tomchen29** [comment]
same issue here! Does anyone figure out how to resolve it?

**Comment by tomchen29** [comment]
Guess I find the reason. The pipeline is a "batch" type job, not a "streaming" type job. Therefore the BigQuery table is only created after the job is finished
