### ISSUE TITLE
Chapter 9 ./create_small.sh bucket name

### ISSUE THREAD

**Issue by tmreic** [GoogleCloudPlatform/data-science-on-gcp#67]
When i try to run ./create_small.sh valid-bucket name on cloud shell i get the following error.
i tried to change the director for writing csv files to be cloud storage but no luck. Still get same exception.  

https://github.com/tmreic/data-science-on-gcp/blob/master/09_cloudml/create_small.sh

@cloudshell:~/data-science-on-gcp/09_cloudml $ ./create_small.sh bucket
CommandException: Destination URL must name a directory, bucket, or bucket
subdirectory for the multiple source form of the cp command.
head: cannot open 'full.csv' for reading: No such file or directory
rm: cannot remove 'full.csv': No such file or directory
CommandException: Destination URL must name a directory, bucket, or bucket
subdirectory for the multiple source form of the cp command.
head: cannot open 'full.csv' for reading: No such file or directory
rm: cannot remove 'full.csv': No such file or directory

**Comment by lakshmanok** [comment]
You need to supply your own bucket to the script. Create a bucket if necessary. See this page for details: https://cloud.google.com/storage/docs/quickstart-console
