### ISSUE TITLE
Chapter 2 - Error while trying to run the ingest app on App Engine: first service must be 'default' service

### ISSUE THREAD

**Issue by johnsyin97** [GoogleCloudPlatform/data-science-on-gcp#68]
> ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: The first service (module) you upload to a new application must be the 'default' service (module). Please upload a version of the 'default' service (module) before uploading a version for the 'flights' service (module). See the documentation for more information. Python: (https://developers.google.com/appengine/docs/python/modules/#Python_Uploading%%20modules) Java: (https://developers.google.com/appengine/docs/java/modules/#Java_Uploading%%20modules)

Shall I change the service name to default?

**Comment by lakshmanok** [comment]
I think you missed the step to initialize app engine:
> 
Initialize a default AppEngine application in your project by running ./init_appengine.sh.
