### ISSUE TITLE
Chapter 2 Why Pub sub is used with cloud functions?

### ISSUE THREAD

**Issue by kinjaldand** [GoogleCloudPlatform/data-science-on-gcp#78]
The last line of chap says: "**_Note also that the program creates a Cloud Pub/Sub topic and subscription. These are needed for Cloud Functions._**" Can somebody put some light on this? I am assuming scheduler automatically triggers cloud functions based on time specified. In that case, how does Pub/Sub come into picture? How it works here? Is it neccessary? Any leads appreciated.

**Comment by lakshmanok** [comment]
Change events are delivered with Pub/Sub notifications from Cloud Storage. See: https://cloud.google.com/functions/docs/calling/storage
