### ISSUE TITLE
Chapter 7: cloning GitHub in Jupyter

### ISSUE THREAD

**Issue by eliot1785** [GoogleCloudPlatform/data-science-on-gcp#79]
Hi, I'm on Chapter 7 and this sentence doesn't really make sense to me:

> We can then start an SSH tunnel, a Chrome session via the network proxy, and browse to port 8080 on the master node of the cluster. In Jupyter, we then can clone the GitHub repository and start off a new notebook.

I previously went through Chapter 6 without problems, but it isn't clear to me what we're meant to do here. I know how to sign into the master node using SSH in Chrome, which I assume is the "Chrome session via the network proxy." But do you mean that we're supposed to browse to port 8080 within that SSH session somehow? That doesn't quite make sense to me because 8080 isn't an SSH port. What am I missing?

I tried just doing git clone within a Jupyter notebook that I accessed through Web Interfaces as explained in Chapter 6, but git clone isn't valid syntax within a Jupyter notebook. So I'm a bit lost. Thanks for any help you can provide!

**Comment by lakshmanok** [comment]
This workflow has now become simplified.  Go to https://console.cloud.google.com/ai-platform/notebooks
and start a Dataproc Hub instance to your Dataproc cluster.
