### ISSUE TITLE
Many Chapter 9 issues

### ISSUE THREAD

**Issue by eliot1785** [GoogleCloudPlatform/data-science-on-gcp#81]
There are a lot of issues that make following along with Chapter 9 difficult to impossible.

When submitting the exact code that you have in this repository with the following command:

```
gcloud ai-platform jobs submit training $JOBNAME \      
--region=$REGION \
--module-name=trainer.task \
--package-path=$(pwd)/flights/trainer \
--job-dir=$OUTPUT_DIR \
--runtime-version=1.14 \
--staging-bucket=gs://$BUCKET \
--master-machine-type=n1-standard-4 \
--scale-tier=CUSTOM \
-- \
--bucket=$BUCKET --num_examples=100000 --func=linear
```

It doesn't work due to some error that I don't understand:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/.local/lib/python2.7/site-packages/trainer/task.py", line 105, in <module>
    model.train_and_evaluate(func_to_call)
  File "/root/.local/lib/python2.7/site-packages/trainer/model.py", line 220, in train_and_evaluate
    callbacks=[cp_callback])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/training.py", line 780, in fit
    steps_name='steps_per_epoch')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/training_arrays.py", line 274, in model_iteration
    batch_outs = f(actual_inputs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/backend.py", line 3292, in __call__
    run_metadata=self.run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
FailedPreconditionError: Table not initialized.
	 [[{{node features/carrier_indicator/hash_table_Lookup/LookupTableFindV2}}]]
```

There are more issues where that came from. I had to comment out `import hypertune` because that isn't available from pip. Also, the command in the book says to use `--runtime-version 2.0` but that isn't even a publicly available version (I fell back to 1.14 - not sure if that's the reason for this error). 

To address this I tried to fall back to the commands that you use in the GitHub instead of the ones you list in the book, but your README lists scripts (e.g. `retrain_cloud.sh`) that don't even exist in the repository, and more importantly I can't figure out how these scripts line up with what I'm reading in the book.

On the whole while I've been able to follow along with the book up to this point, I can't really do it with Chapter 9.

**Comment by lakshmanok** [comment]
Sorry, I forgot to update the README.md in ch09.  Can you try with the updated instructions?
You are right: 2.0 support is not public yet. so the script uses a container to get 2.0.

**Comment by eliot1785** [comment]
I tried it but it doesn't work because your script is looking for an image in `IMAGE=gcr.io/$PROJECT/flights_training_container` but our project won't have that image, only your project has that image. Maybe if you made it publicly available?

**Comment by lakshmanok** [comment]
Updated the README.md with the missing instruction to create the Docker image:
```
cd 09_cloudml/flights
bash push_docker.sh
````

Also, if you want to see my actual steps, see the notebook:   flights_caip.ipynb

**Comment by eliot1785** [comment]
Pushing docker addressed that issue, thanks - I was able to upload the model to Cloud ML. However, when I try to get a prediction (either using your prediction script or even just doing predictions from the GCP console) I get the following error:

```
{
  "error": "Prediction failed: Error during model execution: AbortionError(code=StatusCode.FAILED_PRECONDITION, details=\"Table already initialized.\n\t [[{{node StatefulPartitionedCall_9/StatefulPartitionedCall/model/features/carrier_indicator/carrier_lookup/hash_table/table_init/LookupTableImportV2}}]]\")"
}
```

Notably, even though I am now training with your Docker image, I noticed that the model that gets deployed when using your deploy script is still using TensorFlow 1.14, which I'm guessing has something to do with the error since this is a little similar (a table-related error) to the error I saw in training before using your Docker image.

**Comment by cabrossman** [comment]
> Pushing docker addressed that issue, thanks - I was able to upload the model to Cloud ML. However, when I try to get a prediction (either using your prediction script or even just doing predictions from the GCP console) I get the following error:
> 
> ```
> {
>   "error": "Prediction failed: Error during model execution: AbortionError(code=StatusCode.FAILED_PRECONDITION, details=\"Table already initialized.\n\t [[{{node StatefulPartitionedCall_9/StatefulPartitionedCall/model/features/carrier_indicator/carrier_lookup/hash_table/table_init/LookupTableImportV2}}]]\")"
> }
> ```
> 
> Notably, even though I am now training with your Docker image, I noticed that the model that gets deployed when using your deploy script is still using TensorFlow 1.14 (according to the GCP console), which I'm guessing has something to do with the error since this is a little similar (a table-related error) to the error I saw in training before using your Docker image.

Try to update this command below to use `runtime-version=1.15`...
gcloud ai-platform versions create --model=$MODEL_NAME tf2_15 --async        --framework=tensorflow --python-version=3.5 --runtime-version=1.15        --origin=$EXPORT_PATH --staging-bucket=gs://$BUCKET

**Comment by lakshmanok** [comment]
Thanks for your patience.  Now that Cloud AI Platform supports Python 3.7 and TensorFlow 2.1, all these issues are fixed. We don't need special-purpose Docker image and simply following the instructions in the book (update TF and Python version appropriate) works. I've updated the source repo.
