### ISSUE TITLE
Chapter4: df06.py / simevents table is empty

### ISSUE THREAD

**Issue by Tsunemo** [GoogleCloudPlatform/data-science-on-gcp#85]
I can't have data in simevents table of Bigquery.
Something is wrong with flights:tzcorr because of following.  
```
Output collections
flights:tzcorr/flights:tzcorr.out0
```

<img width="974" alt="スクリーンショット 2019-12-22 19 56 37" src="https://user-images.githubusercontent.com/42575557/71320881-33a10700-24f5-11ea-9a07-7733e9de2f70.png">

Anyone help me?

**Comment by chan-p** [comment]
me too. . .
The output collections of AsDict section is zero KB.
