### ISSUE TITLE
Chap6: quantization.ipynb , Py4JJavaError

### ISSUE THREAD

**Issue by mokpolar** [GoogleCloudPlatform/data-science-on-gcp#88]
I see this error in running quantization.ipynb.

Flights = spark.read\
.schema(schema)\
.csv (inputs)

Py4JJavaError: An error has been detected while calling o32.csv.: java.io.IOException: No FileSystem for Schema: gs ...

Why is this error happening?

**Comment by lakshmanok** [comment]
Looks like the cloud storage connector is not installed.  Are you running on Dataproc?
