### ISSUE TITLE
Chapter 2 - Optional Tasks

### ISSUE THREAD

**Issue by andresgalarza-astro** [GoogleCloudPlatform/data-science-on-gcp#89]
Hello there!
I'm currently following this tutorial and when I ran ./deploy_cf.sh after setting the token and modifying it on main.py I got the following error

ingest_flights_vNdUIIMPCAy5v8715MV361o4TTdDBssZ
Allow unauthenticated invocations of new function
[ingest_flights_vNdUIIMPCAy5v8715MV361o4TTdDBssZ]? (y/N)?  y
Deploying function (may take a while - up to 2 minutes)...failed.
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Function failed on loading user code. Error message: File main.py is expected to contain a functi
on named ingest_flights_vNdUIIMPCAy5v8715MV361o4TTdDBssZ

**Comment by ryanjclark** [comment]
Same issue here

**Comment by brenterprises** [comment]
Is the issue that we need to rename the function after the new token. So we have to manually rename the function in main.py as the new token. 

AttributeError: module 'main' has no attribute 'ingest_flights_<token>'

**Comment by kaijennissen** [comment]
One solution is to add the **--entry-point** flag to the deploy_cf.sh.
`gcloud functions deploy $URL  --entry-point ingest_flight --runtime python37 --trigger-http --timeout 480s`

**Comment by lakshmanok** [comment]
Thanks, can you submit a pull request with the change?
