### ISSUE TITLE
Chapter 2 Transtats Server using weak DH Key

### ISSUE THREAD

**Issue by dylanmpeck** [GoogleCloudPlatform/data-science-on-gcp#93]
There's a url (https://www.transtats.bts.gov/DownLoad_Table.asp?Table_ID=236&Has_Group=3&Is_Zipped=0) used in chapter 2 that's now hitting a "DH key too small" error when trying to open or curl. I made a PR with a workaround for one instance, but if possible, upgrading the server might be a better solution as accessing this server through curl or urlopen is in multiple files.

**Comment by brenterprises** [comment]
You need a similar solution for the monthlyupdate/main.py. I am getting a cipher issue as well (trying to run the end of Chapter 2 code excercise).

urllib2.URLError: <urlopen error [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:727)>
