### ISSUE TITLE
Chapter 2: call_cf.sh not working

### ISSUE THREAD

**Issue by kaijennissen** [GoogleCloudPlatform/data-science-on-gcp#98]
For some reason the call_cf.sh script does not work as expected. I've played a little with the year and month specified in the file, f.e. changed the year to 2016 and tried various values for the month. When running the file as bash script no files are added to the bucket.
I've no idea why it fails because running the commands line by line in the shell works just fine and the requested month is added to the bucket.

**Comment by lakshmanok** [comment]
thanks for fixing in PR 97!

**Comment by kaijennissen** [comment]
Unfortunately PR 97 does not fix this issue.

**Comment by lakshmanok** [comment]
try now. The PATH variable was getting clobbered.

**Comment by kaijennissen** [comment]
I've already used the latest version with the UPATH variable. There is no error message but the cloud function is not triggered since there are no entries in the logs. While supplying the content of the /tmp/message file to the testing section of the cloud function works just fine.

**Comment by kaijennissen** [comment]
The problem was the URL variable in the curl command.

**Comment by lakshmanok** [comment]
fixed the URL ...

lak
